services:
  app:
    image: node:alpine
    entrypoint: /bin/sh
    tty: true # https://github.com/evanw/esbuild/commit/4267bef78ff0177d77a66f7e2b36dd03f4bc8de1
    command:
      - -c
      - |
        tee /index.js << EOF > /dev/null
        console.log("it is something from `uname -a`");
        setInterval(() => document.querySelector("#client").innerHTML = Date.now(), 1500);
        setInterval(() => { fetch("/echo/foo/bar").then(x => x.json()).then(x => document.querySelector("#server").innerHTML = JSON.stringify(x,null,2)); }, 1500);
        EOF

        npx -y esbuild@0.12.17 /index.js --bundle --minify --serve=80

  echo:
    image: node:alpine
    command:
      - -e
      - |
        require("http").createServer((req,res) => {
          const {query, pathname, path} = require("url").parse(req.url, true);
          res.end(JSON.stringify({query,pathname,path,now: Date.now()}));
          return;
        }).listen(80);

  nginx:
    image: nginx:alpine
    ports:
      - '3000:80'
    entrypoint: /bin/sh
    command:
      - -c
      - |
        tee index.html << EOF >/dev/null

        <h1>Verant Demo</h1>
        <h2>Server side</h2>
        <code id="server"></code>
        <h2>Client side</h2>
        <pre id="client"></pre>

        <script src="index.js"></script>

        EOF

        tee hello.js << EOF >/dev/null
        function world(r) {
          r.headersOut['content-type'] = 'application/json';
          r.return(200, JSON.stringify({timestamp: Date.now(), msg: 'Hello World from njs!', env: process.env}));
        }
        export default {world};
        EOF

        tee /etc/nginx/nginx.conf << EOF > /dev/null
        user  nginx;
        worker_processes  auto;

        error_log  /var/log/nginx/error.log notice;
        pid        /var/run/nginx.pid;

        load_module modules/ngx_http_js_module.so;

        events {
            worker_connections  1024;
        }

        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            log_format  main  '\$$remote_addr - \$$remote_user [\$$time_local] "\$$request" '
                              '\$$status \$$body_bytes_sent "\$$http_referer" '
                              '"\$$http_user_agent" "\$$http_x_forwarded_for"';

            access_log  /var/log/nginx/access.log  main;
            sendfile        on;
            keepalive_timeout  65;
            gzip  on;

            js_path /;
            js_import hello.js;

            server {
              listen  80;

              location / {
                root   /;
                index  index.html;
              }

              location /index.js {
                proxy_pass http://app;
              }

              location /echo {
                proxy_pass http://echo;
              }

              location /hello {
                js_content hello.world;
              }

              location ~ /posts/(.*) {
                rewrite ^/posts(.*)$$ $$1 break;
                proxy_pass http://echo;
              }
            }
        }
        EOF

        nginx -T && nginx -g 'daemon off;'
